# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5d4a2a754f7b0e243c6e8e0088c756f6854d0cb12e9a17322b856d54997293afc68e944872df852a60a33bc3bd88673ecf53d55505335d24e773d3e14258a6c

test:
  secret_key_base: cdddc5fe2dadff8c9606e4c3ae8b2fc38f5aa8d6934c244389289d16767b87548b83ed3c1bfcca4e300a09cb6be9da7720e78952e96c939f8524315b3a29c487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
